### PR TITLE
Fix panic on short outputs

### LINKED ISSUE #1: Panic on default blake2b params with 32 byte output
Reported on Twitter: https://twitter.com/Elichai2/status/1336999936936849411 by @elichai

> It panics on this code:
> ```
> blake, _ := blake2b.NewDigest(nil, nil, nil, 32)
> blake.Write(buf[:])
> blake.Sum(nil)
>```

This feels like it's probably going to be an uninitialized slice somewhere. But it's surprising that tests or usage haven't caught it; I guess they all define some parameter or other, that being the motivation for the library. Whoops.

### PR DESCRIPTION
**Pull request by gtank**
Previously, we tried to write a full-sized output regardless of what was asked for. Now we write only as many bytes as requested.

Closes https://github.com/gtank/blake2/issues/1

### CODE REVIEW

File: blake2b/blake2b.go [hunk 1]
```diff
@@ -333,15 +333,14 @@ func (d *Digest) finalize(out []byte) error {
...
-	putU64LE(out[6*8:], dCopy.h[6])
-	putU64LE(out[7*8:], dCopy.h[7])
+	var shift uint
+	var mask uint64
+
+	for offset := 0; offset < len(out); offset++ {
+		shift = 8 * (uint(offset) % 8)
+		mask = uint64(0xFF << shift)
+		out[offset] = byte((dCopy.h[offset/8] & mask) >> shift)
+	}
```
Comment (elichai) [inline blake2b/blake2b.go:343]: Sadly this is going to affect performance :(
https://github.com/golang/go/issues/40704

Comment (gtank) [reply blake2b/blake2b.go:343]: Ugh, yes it does, and it's fairly harsh. But since `finalize` is only called once per `Sum` I think correctness wins over performance here. It won't affect any longer series of writes and compressions, and rough benchmarking confirmed the expected result that this mostly hurts very small write tasks where the finalization dominates:

```
$ benchstat not-fixed fixed 
name          old time/op    new time/op    delta
Hash8Bytes-4     361ns ± 0%     459ns ± 1%  +27.33%  (p=0.000 n=9+10)
Hash1K-4        1.77µs ± 0%    1.87µs ± 0%   +5.62%  (p=0.000 n=10+10)
Hash8K-4        12.9µs ± 1%    13.0µs ± 1%   +0.74%  (p=0.001 n=9+10)

name          old speed      new speed      delta
Hash8Bytes-4  22.2MB/s ± 0%  17.4MB/s ± 1%  -21.46%  (p=0.000 n=9+10)
Hash1K-4       578MB/s ± 0%   547MB/s ± 0%   -5.32%  (p=0.000 n=10+10)
Hash8K-4       633MB/s ± 1%   629MB/s ± 1%   -0.73%  (p=0.001 n=9+10)
```

Unfortunately hashing small amounts of data (say, 32 bytes of key) is my main use case. So I'd happily take a PR with a better solution, but I figured "panics on totally reasonable inputs to a top level API" needed to be fixed :)

Comment (gtank) [reply blake2b/blake2b.go:343]: Overall, I think if anyone needs a **lot** more throughput from this, the most expedient solution would be the assembly from `x/crypto`. I dislike that, but it will likely double the performance.
